package com.example.Kodify.entities

import com.example.Kodify.AuditTrail
import com.example.Kodify.enums.UserRole
import jakarta.persistence.*
import java.util.*

@Entity
@Table(name = "app_users")
data class User(

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    val id: UUID? = null, // this is the primary key

    val auth0id: String,
    // Auth0 is an external identity provider
    // the id generated by Auth0 will not be the primary identifier for each user

    val name: String,

    @Column(unique = true, nullable = false)
    val email: String,

    @Enumerated(EnumType.STRING)
    val role: UserRole,

    ) : AuditTrail()
